#!/bin/csh -f
alias clang++='clang++-3.5 -std=c++11'
@ a = 360
@ init = $a 
while ( $a < 361 )
	mkdir $a
	cd $a
	@ ifcreate = 0; 
	sed "s/xxx/$a/; s/xxxnew/$a/ ; s/xxclustering/step<-1/ ; s/xxnstep/step<=50000000/ ; s/xxcreate/$ifcreate/ ; s/xxrestart/0/ ; s/xxthermo/0/ ; s/xxcluster_restart/0/ ; s/xx_rotation/1/ ; s/xx_diffusion/1/ " ../../simulate.cpp > simulate.cpp
	sed "s/xxshift/0/ ; s/xxclustering/1/" ../../pairforce.h > pairforce.h

  cp ../../rigid_force.h .
  cp ../../structure_definitions.h .
  cp ../../rigid_force.cpp .
  cp ../../vctr3D.h .
  cp ../../vctr4D.h .
  cp ../../X2mu.cpp .
  cp ../../defs.h .

  if ( $ifcreate == 1 ) then
		rm -f log
  endif
  
# g++ -std=c++11 X2mu.cpp -O2 -o X2mu.out -llapack	
# ./X2mu.out >>& log -a &
 
# wait
  
 g++ -std=c++11 simulate.cpp rigid_force.cpp -O2 -o simulate.out -llapack
 ./simulate.out >>& log -a &

  cd ..
  @ a = $a + 1
end


