#!/bin/csh -f
alias clang++='clang++-3.5 -std=c++11'
@ a = 18
while ( $a < 19 )
mkdir $a
  cd $a
  sed "s/xxx/$a/ ; s/xxxnew/$a/ ; s/xxclustering/step<-1/ ; s/xxnstep/step<1000/ ; s/xxcreate/1/ ; s/xxrestart/0/ ; s/xxthermo/0/ ; s/xxcluster_restart/0/ " ../../BD_3D_rigid_rotation_optimized.cpp > BD_3D_rigid_rotation_optimized.cpp
  sed "s/xxshift/1/ " ../../pairforce.h > pairforce.h

  cp ../../rigid_force.h .
  cp ../../structure_definitions.h .
  cp ../../rigid_force.cpp .
  cp ../../vctr3D.h .
  cp ../../vctr4D.h .
  cp ../../defs.h .

  icpc -std=c++11 BD_3D_rigid_rotation_optimized.cpp rigid_force.cpp -pg -O3 -o BD_3D_rigid_rotation_optimized.out
    ./BD_3D_rigid_rotation_optimized.out | tee log

  cd ..
  @ a = $a + 1
end

@ a = 18
while ( $a < 19 )
  cd $a
  sed "s/xxx/$a/ ; s/xxxnew/$a/ ; s/xxclustering/step>1000/ ; s/xxnstep/step<15000000/ ; s/xxcreate/0/ ; s/xxrestart/1/ ; s/xxthermo/step<1000/ ; s/xxcluster_restart/0/" ../../BD_3D_rigid_rotation_optimized.cpp > BD_3D_rigid_rotation_optimized.cpp
  sed "s/xxshift/0/ " ../../pairforce.h > pairforce.h

  cp ../../rigid_force.h .
  cp ../../structure_definitions.h .
  cp ../../rigid_force.cpp .
  cp ../../vctr3D.h .
  cp ../../vctr4D.h .
  cp ../../defs.h .
  cp ../diffusion_tensor/hydro++input.txt .
  
  icpc -std=c++11 BD_3D_rigid_rotation_optimized.cpp rigid_force.cpp -pg -O3 -o BD_3D_rigid_rotation_optimized.out
    ./BD_3D_rigid_rotation_optimized.out | tee log

  cd ..
  @ a = $a + 1
end
