#!/bin/csh -f
alias clang++='clang++-3.5 -std=c++11'
@ a = 454
@ init = $a 
while ( $a < 455 )
	mkdir $a
	cd $a
	@ ifcreate = 1; 

  if ( $ifcreate == 1 ) then
		rm -f log
  endif

 ./${a}_simulate.out >>& log -a &

  cd ..
  @ a = $a + 1
end
